name: Mirror to GitLab

on:
  push:
    branches:
      - main  # Замените на master, если ваша главная ветка называется master

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git push --force https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/aev-nox/aev-nox.git HEAD:refs/heads/main
